# Sử dụng một hình ảnh chứa Node.js
FROM node:16

# Tạo thư mục làm việc trong container
WORKDIR /usr/src/app

# Sao chép package.json và package-lock.json vào thư mục làm việc
COPY package*.json ./

# Cài đặt các dependency
RUN npm install

# Sao chép toàn bộ mã nguồn ứng dụng vào thư mục làm việc
COPY . .

# Mở cổng 3000, nếu ứng dụng của bạn chạy trên cổng khác, thay đổi số này
EXPOSE 3000

# Khởi động ứng dụng khi container được chạy
CMD ["npm", "start"]
