FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./mime.types /etc/nginx/mime.types

COPY ./dist/id/ /usr/share/nginx/html

# Cổng mặc định cho Nginx là 80, bạn có thể sửa đổi nếu cần
EXPOSE 80
